# Google (built-in provider) — scope에 openid 포함 시 OIDC로 동작
# spring.security.oauth2.client.registration.google.client-id=test
# spring.security.oauth2.client.registration.google.client-secret=abc
# spring.security.oauth2.client.registration.google.scope=openid,email,profile

# spring.security.oauth2.client.registration.slack.client-name=Slack
# spring.security.oauth2.client.registration.slack.client-id=test
# spring.security.oauth2.client.registration.slack.client-secret=abc
# spring.security.oauth2.client.registration.slack.authorization-grant-type=authorization_code
# spring.security.oauth2.client.registration.slack.scope=openid,email,profile
# spring.security.oauth2.client.registration.slack.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
# spring.security.oauth2.client.provider.slack.authorization-uri=https://slack.com/openid/connect/authorize
# spring.security.oauth2.client.provider.slack.token-uri=https://slack.com/api/openid.connect.token
# spring.security.oauth2.client.provider.slack.user-info-uri=https://slack.com/api/openid.connect.userInfo
# spring.security.oauth2.client.provider.slack.jwk-set-uri=https://slack.com/openid/connect/keys
# spring.security.oauth2.client.provider.slack.user-name-attribute=sub